apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: python-deps-crawler
type: Opaque
data:
  REDIS_PASSWORD: cmVkaXMtc2VjcmV0IQo= # redis-secret!
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: python-deps-crawler
type: Opaque
data:
  POSTGRES_USER: YXBwX3VzZXIK #app_user
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM= # password123 base64
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: python-deps-crawler
type: Opaque
data:
  PGADMIN_USER: YWRtaW5AZXhhbXBsZS5jb20K # admin@example.com
  PGADMIN_PASSWORD: U3VwZXJTZWNyZXQ= # SuperSecret

