apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: python-deps-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:8.0
        command:
          - redis-server
        args:
          - --requirepass
          - $(REDIS_PASSWORD)
        ports:
        - containerPort: 6379
        env:
         - name: REDIS_PASSWORD
           valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: python-deps-crawler
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379